sudo: required
dist: trusty

before_install:
     - sudo apt-get install m4 llvm software-properties-common
     - sudo add-apt-repostiory --yes ppa:avsm/ppa
     - sudo apt-get update -qq
     - sudo apt-get install ocaml menhir
     - sudo apt-get install opam
     - opam init
     - eval `opam config env`
     - opam install llvm3.4 ocamlfind

script:
     - cd source
     - make lepix
     - cd ../
     - ./testall.sh
