sudo: required
dist: trusty

before_install:
     - apt-get update
     - apt-get install m4 llvm software-properties-common
     - apt-get-repostiory --yes ppa:avsm/ppa
     - apt-get update -qq
     - apt-get install ocaml menhir
     - apt-get install opam
     - opam init
     - eval `opam config env`
     - opam install llvm3.4 ocamlfind

script:
     - cd source
     - make lepix
     - cd ../
     - ./testall.sh
