dist: trusty
sudo: required

language: ocaml

before_install:
     - apt-get update
     - apt install -y git python3 build-essential m4 autotools-dev autoconf pkg-config ocaml menhir opam llvm llvm-dev llvm.3.8
     - opam init -y
     - opam install -y depext llvm.3.8

script:
     - ./testall.sh

notifications:
     email:
          on_success: change
          on_failure: change
